default_language_version:
  python: "3.11"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "test_*"
        args: ["-iii", "-ll", "-s=B308,B703"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
            "flake8-type-checking",
            "flake8-implicit-str-concat",
            "flake8-noqa",
            "flake8-return",
            "flake8-secure-coding-standard",
            "flake8-encodings",
            "flake8-use-fstring",
            "flake8-use-pathlib",
          ]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.16.1"
    hooks:
      - id: pylint
        exclude: "test_*"
        args: ["--unsafe-load-any-extension=y"]
        additional_dependencies:
          [pydantic, faker, pytest, hypothesis, odmantic, ormar, beanie]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.0"
    hooks:
      - id: mypy
        exclude: "extension"
        additional_dependencies:
          [pydantic, faker, pytest, hypothesis, odmantic, ormar, beanie]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.293
    hooks:
      - id: pyright
        exclude: "extension"
        additional_dependencies:
          [pydantic, faker, pytest, hypothesis, odmantic, ormar, beanie]
